language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build aylien_news_api.gemspec
  - gem install ./aylien_news_api-5.0.1.gem
