=begin
#AYLIEN News API

#The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 

The version of the OpenAPI document: 3.0
Contact: support@aylien.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for AylienNewsApi::AutocompleteApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AutocompleteApi' do
  before do
    # run before each test
    @api_instance = AylienNewsApi::AutocompleteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutocompleteApi' do
    it 'should create an instance of AutocompleteApi' do
      expect(@api_instance).to be_instance_of(AylienNewsApi::AutocompleteApi)
    end
  end

  # unit tests for list_autocompletes
  # List autocompletes
  # The autocompletes endpoint a string of characters provided to it, and then returns suggested terms that are the most likely full words or strings. The terms returned by the News API are based on parameters the type parameters you can see below. For example, if you provide the autocompletes endpoint with the term &#x60;New York C&#x60; and select the type &#x60;dbpedia_resources&#x60;, the API will return links to the DBpedia resources &#x60;New_York_City&#x60;, &#x60;New_York_City_Subway&#x60;, &#x60;New_York_City_Police_Department&#x60;, and so on. 
  # @param type This parameter is used for defining the type of autocompletes. 
  # @param term This parameter is used for finding autocomplete objects that contain the specified value. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language This parameter is used for autocompletes whose language is the specified value. It supports [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes. 
  # @option opts [Integer] :per_page This parameter is used for specifying number of items in each page. 
  # @return [Autocompletes]
  describe 'list_autocompletes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
