=begin
#AYLIEN News API

#The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 

The version of the OpenAPI document: 3.0
Contact: support@aylien.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.3-SNAPSHOT

=end

require 'cgi'

module AylienNewsApi
  class ClusterApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List Clusters
    # The clusters endpoint is used to return clusters based on parameters you set in your query. 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<Integer>] :id This parameter is used for finding clusters by cluster id. 
    # @option opts [Array<Integer>] :id2 This parameter is used for excluding clusters by cluster id. 
    # @option opts [Integer] :story_count_min This parameter is used for finding clusters with more than or equal to a specific amount of stories associated with them. 
    # @option opts [Integer] :story_count_max This parameter is used for finding clusters with less than or equal to a specific amount of stories associated with them. 
    # @option opts [String] :time_start This parameter is used for finding clusters whose creation time is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :time_end This parameter is used for finding clusters whose creation time is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :earliest_story_start This parameter is used for finding clusters whose publication date of its earliest story is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :earliest_story_end This parameter is used for finding clusters whose publication date of its earliest story is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :latest_story_start This parameter is used for finding clusters whose publication date of its latest story is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :latest_story_end This parameter is used for finding clusters whose publication date of its latest story is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [Array<String>] :location_country This parameter is used for finding clusters belonging to a specific country. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :location_country2 This parameter is used for excluding clusters belonging to a specific country. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :_return This parameter is used for specifying return fields.
    # @option opts [String] :sort_by This parameter is used for changing the order column of the results. You can read about sorting results [here](https://newsapi.aylien.com/docs/sorting-results).  (default to 'published_at')
    # @option opts [String] :sort_direction This parameter is used for changing the order direction of the result. You can read about sorting results [here](https://newsapi.aylien.com/docs/sorting-results).  (default to 'desc')
    # @option opts [String] :cursor This parameter is used for finding a specific page. You can read more about pagination of results [here](https://newsapi.aylien.com/docs/pagination-of-results).  (default to '*')
    # @option opts [Integer] :per_page This parameter is used for specifying number of items in each page You can read more about pagination of results [here](https://newsapi.aylien.com/docs/pagination-of-results)  (default to 10)
    # @return [Clusters]
    def list_clusters(opts = {})
      data, _status_code, _headers = list_clusters_with_http_info(opts)
      data
    end

    # List Clusters
    # The clusters endpoint is used to return clusters based on parameters you set in your query. 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<Integer>] :id This parameter is used for finding clusters by cluster id. 
    # @option opts [Array<Integer>] :id2 This parameter is used for excluding clusters by cluster id. 
    # @option opts [Integer] :story_count_min This parameter is used for finding clusters with more than or equal to a specific amount of stories associated with them. 
    # @option opts [Integer] :story_count_max This parameter is used for finding clusters with less than or equal to a specific amount of stories associated with them. 
    # @option opts [String] :time_start This parameter is used for finding clusters whose creation time is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :time_end This parameter is used for finding clusters whose creation time is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :earliest_story_start This parameter is used for finding clusters whose publication date of its earliest story is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :earliest_story_end This parameter is used for finding clusters whose publication date of its earliest story is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :latest_story_start This parameter is used for finding clusters whose publication date of its latest story is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :latest_story_end This parameter is used for finding clusters whose publication date of its latest story is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [Array<String>] :location_country This parameter is used for finding clusters belonging to a specific country. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :location_country2 This parameter is used for excluding clusters belonging to a specific country. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :_return This parameter is used for specifying return fields.
    # @option opts [String] :sort_by This parameter is used for changing the order column of the results. You can read about sorting results [here](https://newsapi.aylien.com/docs/sorting-results). 
    # @option opts [String] :sort_direction This parameter is used for changing the order direction of the result. You can read about sorting results [here](https://newsapi.aylien.com/docs/sorting-results). 
    # @option opts [String] :cursor This parameter is used for finding a specific page. You can read more about pagination of results [here](https://newsapi.aylien.com/docs/pagination-of-results). 
    # @option opts [Integer] :per_page This parameter is used for specifying number of items in each page You can read more about pagination of results [here](https://newsapi.aylien.com/docs/pagination-of-results) 
    # @return [Array<(Clusters, Integer, Hash)>] Clusters data, response status code and response headers
    def list_clusters_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ClusterApi.list_clusters ...'
      end
      if @api_client.config.client_side_validation && !opts[:'story_count_min'].nil? && opts[:'story_count_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"story_count_min"]" when calling ClusterApi.list_clusters, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'story_count_max'].nil? && opts[:'story_count_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"story_count_max"]" when calling ClusterApi.list_clusters, must be greater than 0.'
      end

      allowable_values = ["id", "time", "summary", "category", "story_count", "earliest_story", "latest_story", "representative_story", "location_country"]
      if @api_client.config.client_side_validation && opts[:'_return'] && !opts[:'_return'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"_return\", must include one of #{allowable_values}"
      end
      allowable_values = ["time", "story_count", "earliest_story", "latest_story"]
      if @api_client.config.client_side_validation && opts[:'sort_by'] && !allowable_values.include?(opts[:'sort_by'])
        fail ArgumentError, "invalid value for \"sort_by\", must be one of #{allowable_values}"
      end
      allowable_values = ["asc", "desc"]
      if @api_client.config.client_side_validation && opts[:'sort_direction'] && !allowable_values.include?(opts[:'sort_direction'])
        fail ArgumentError, "invalid value for \"sort_direction\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling ClusterApi.list_clusters, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling ClusterApi.list_clusters, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/clusters'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'id[]'] = @api_client.build_collection_param(opts[:'id'], :multi) if !opts[:'id'].nil?
      query_params[:'!id[]'] = @api_client.build_collection_param(opts[:'id2'], :multi) if !opts[:'id2'].nil?
      query_params[:'story_count.min'] = opts[:'story_count_min'] if !opts[:'story_count_min'].nil?
      query_params[:'story_count.max'] = opts[:'story_count_max'] if !opts[:'story_count_max'].nil?
      query_params[:'time.start'] = opts[:'time_start'] if !opts[:'time_start'].nil?
      query_params[:'time.end'] = opts[:'time_end'] if !opts[:'time_end'].nil?
      query_params[:'earliest_story.start'] = opts[:'earliest_story_start'] if !opts[:'earliest_story_start'].nil?
      query_params[:'earliest_story.end'] = opts[:'earliest_story_end'] if !opts[:'earliest_story_end'].nil?
      query_params[:'latest_story.start'] = opts[:'latest_story_start'] if !opts[:'latest_story_start'].nil?
      query_params[:'latest_story.end'] = opts[:'latest_story_end'] if !opts[:'latest_story_end'].nil?
      query_params[:'location.country'] = @api_client.build_collection_param(opts[:'location_country'], :multi) if !opts[:'location_country'].nil?
      query_params[:'!location.country'] = @api_client.build_collection_param(opts[:'location_country2'], :multi) if !opts[:'location_country2'].nil?
      query_params[:'return[]'] = @api_client.build_collection_param(opts[:'_return'], :multi) if !opts[:'_return'].nil?
      query_params[:'sort_by'] = opts[:'sort_by'] if !opts[:'sort_by'].nil?
      query_params[:'sort_direction'] = opts[:'sort_direction'] if !opts[:'sort_direction'].nil?
      query_params[:'cursor'] = opts[:'cursor'] if !opts[:'cursor'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/xml'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'Clusters' 

      # auth_names
      auth_names = opts[:auth_names] || ['app_id', 'app_key']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ClusterApi#list_clusters\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
