=begin
#AYLIEN News API

#The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 

The version of the OpenAPI document: 3.0
Contact: support@aylien.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.3-SNAPSHOT

=end

require 'cgi'

module AylienNewsApi
  class TimeSeriesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List time series
    # The time series endpoint allows you to track information contained in stories over time. This information can be anything from mentions of a topic or entities, sentiment about a topic, or the volume of stories published by a source, to name but a few. The full list of parameters is given below. Using the [Date Math Syntax](https://newsapi.aylien.com/docs/working-with-dates), you can easily set your query to return information from any time period, from the current point in time to when the News API started collecting stories. The returned information can be rounded to a time also specified by you, for example by setting the results into hourly, daily, or weekly data points. 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<Integer>] :id This parameter is used for finding stories by story id. 
    # @option opts [Array<Integer>] :id2 This parameter is used for excluding stories by story id. 
    # @option opts [String] :title This parameter is used for finding stories whose title contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :body This parameter is used for finding stories whose body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :text This parameter is used for finding stories whose title or body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_title This parameter is used for finding stories whose translation title contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_body This parameter is used for finding stories whose translation body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_text This parameter is used for finding stories whose translation title or body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [Array<String>] :language This parameter is used for finding stories whose language is the specified value. It supports [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes. 
    # @option opts [Array<String>] :language2 This parameter is used for excluding stories whose language is the specified value. It supports [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes. 
    # @option opts [String] :categories_taxonomy This parameter is used for defining the type of the taxonomy for the rest of the categories queries. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Boolean] :categories_confident This parameter is used for finding stories whose categories are confident. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories).  (default to true)
    # @option opts [Array<String>] :categories_id This parameter is used for finding stories by categories id. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_id2 This parameter is used for excluding stories by categories id. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_label This parameter is used for finding stories by categories label. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_label2 This parameter is used for excluding stories by categories label. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<Integer>] :categories_level This parameter is used for finding stories by categories level. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<Integer>] :categories_level2 This parameter is used for excluding stories by categories level. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :entities_title_text This parameter is used to find stories based on the specified entities &#x60;text&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_text2 This parameter is used to exclude stories based on the specified entities &#x60;text&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_type This parameter is used to find stories based on the specified entities &#x60;type&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_type2 This parameter is used to exclude stories based on the specified entities &#x60;type&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_links_dbpedia This parameter is used to find stories based on the specified entities dbpedia URL in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_links_dbpedia2 This parameter is used to exclude stories based on the specified entities dbpedia URL in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_text This parameter is used to find stories based on the specified entities &#x60;text&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_text2 This parameter is used to exclude stories based on the specified entities &#x60;text&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_type This parameter is used to find stories based on the specified entities &#x60;type&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_type2 This parameter is used to exclude stories based on the specified entities &#x60;type&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_links_dbpedia This parameter is used to find stories based on the specified entities dbpedia URL in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_links_dbpedia2 This parameter is used to exclude stories based on the specified entities dbpedia URL in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [String] :sentiment_title_polarity This parameter is used for finding stories whose title sentiment is the specified value. 
    # @option opts [String] :sentiment_title_polarity2 This parameter is used for excluding stories whose title sentiment is the specified value. 
    # @option opts [String] :sentiment_body_polarity This parameter is used for finding stories whose body sentiment is the specified value. 
    # @option opts [String] :sentiment_body_polarity2 This parameter is used for excluding stories whose body sentiment is the specified value. 
    # @option opts [Integer] :media_images_count_min This parameter is used for finding stories whose number of images is greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_count_max This parameter is used for finding stories whose number of images is less than or equal to the specified value. 
    # @option opts [Integer] :media_images_width_min This parameter is used for finding stories whose width of images are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_width_max This parameter is used for finding stories whose width of images are less than or equal to the specified value. 
    # @option opts [Integer] :media_images_height_min This parameter is used for finding stories whose height of images are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_height_max This parameter is used for finding stories whose height of images are less than or equal to the specified value. 
    # @option opts [Integer] :media_images_content_length_min This parameter is used for finding stories whose images content length are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_content_length_max This parameter is used for finding stories whose images content length are less than or equal to the specified value. 
    # @option opts [Array<String>] :media_images_format This parameter is used for finding stories whose images format are the specified value. 
    # @option opts [Array<String>] :media_images_format2 This parameter is used for excluding stories whose images format are the specified value. 
    # @option opts [Integer] :media_videos_count_min This parameter is used for finding stories whose number of videos is greater than or equal to the specified value. 
    # @option opts [Integer] :media_videos_count_max This parameter is used for finding stories whose number of videos is less than or equal to the specified value. 
    # @option opts [Array<Integer>] :author_id This parameter is used for finding stories whose author id is the specified value. 
    # @option opts [Array<Integer>] :author_id2 This parameter is used for excluding stories whose author id is the specified value. 
    # @option opts [String] :author_name This parameter is used for finding stories whose author full name contains the specified value. 
    # @option opts [String] :author_name2 This parameter is used for excluding stories whose author full name contains the specified value. 
    # @option opts [Array<Integer>] :source_id This parameter is used for finding stories whose source id is the specified value. 
    # @option opts [Array<Integer>] :source_id2 This parameter is used for excluding stories whose source id is the specified value. 
    # @option opts [Array<String>] :source_name This parameter is used for finding stories whose source name contains the specified value. 
    # @option opts [Array<String>] :source_name2 This parameter is used for excluding stories whose source name contains the specified value. 
    # @option opts [Array<String>] :source_domain This parameter is used for finding stories whose source domain is the specified value. 
    # @option opts [Array<String>] :source_domain2 This parameter is used for excluding stories whose source domain is the specified value. 
    # @option opts [Array<String>] :source_locations_country This parameter is used for finding stories whose source country is the specified value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_country2 This parameter is used for excluding stories whose source country is the specified value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_state This parameter is used for finding stories whose source state/province is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_state2 This parameter is used for excluding stories whose source state/province is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_city This parameter is used for finding stories whose source city is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_city2 This parameter is used for excluding stories whose source city is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_country This parameter is used for finding stories whose source scopes is the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_country2 This parameter is used for excluding stories whose source scopes is the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_state This parameter is used for finding stories whose source scopes is the specified state/province value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_state2 This parameter is used for excluding stories whose source scopes is the specified state/province value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_city This parameter is used for finding stories whose source scopes is the specified city value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_city2 This parameter is used for excluding stories whose source scopes is the specified city value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_level This parameter is used for finding stories whose source scopes is the specified level value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_level2 This parameter is used for excluding stories whose source scopes is the specified level value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Integer] :source_links_in_count_min This parameter is used for finding stories from sources whose Links in count is greater than or equal to the specified value. You can read more about working with Links in count [here](https://newsapi.aylien.com/docs/working-with-links-in-count). 
    # @option opts [Integer] :source_links_in_count_max This parameter is used for finding stories from sources whose Links in count is less than or equal to the specified value. You can read more about working with Links in count [here](https://newsapi.aylien.com/docs/working-with-links-in-count). 
    # @option opts [Integer] :source_rankings_alexa_rank_min This parameter is used for finding stories from sources whose Alexa rank is greater than or equal to the specified value. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Integer] :source_rankings_alexa_rank_max This parameter is used for finding stories from sources whose Alexa rank is less than or equal to the specified value. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Array<String>] :source_rankings_alexa_country This parameter is used for finding stories from sources whose Alexa rank is in the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Integer] :social_shares_count_facebook_min This parameter is used for finding stories whose Facebook social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_facebook_max This parameter is used for finding stories whose Facebook social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_google_plus_min This parameter is used for finding stories whose Google+ social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_google_plus_max This parameter is used for finding stories whose Google+ social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_linkedin_min This parameter is used for finding stories whose LinkedIn social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_linkedin_max This parameter is used for finding stories whose LinkedIn social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_reddit_min This parameter is used for finding stories whose Reddit social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_reddit_max This parameter is used for finding stories whose Reddit social shares count is less than or equal to the specified value. 
    # @option opts [Array<String>] :clusters This parameter is used for finding stories with belonging to one of clusters in a specific set of clusters You can read more about working with clustering [here](https://newsapi.aylien.com/docs/working-with-clustering). 
    # @option opts [String] :published_at_start This parameter is used for finding stories whose published at time is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates).  (default to 'NOW-7DAYS/DAY')
    # @option opts [String] :published_at_end This parameter is used for finding stories whose published at time is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates).  (default to 'NOW/DAY')
    # @option opts [String] :period The size of each date range is expressed as an interval to be added to the lower bound. It supports Date Math Syntax. Valid options are &#x60;+&#x60; following an integer number greater than 0 and one of the Date Math keywords. e.g. &#x60;+1DAY&#x60;, &#x60;+2MINUTES&#x60; and &#x60;+1MONTH&#x60;. Here are [Supported keywords](https://newsapi.aylien.com/docs/working-with-dates#date-math).  (default to '+1DAY')
    # @return [TimeSeriesList]
    def list_time_series(opts = {})
      data, _status_code, _headers = list_time_series_with_http_info(opts)
      data
    end

    # List time series
    # The time series endpoint allows you to track information contained in stories over time. This information can be anything from mentions of a topic or entities, sentiment about a topic, or the volume of stories published by a source, to name but a few. The full list of parameters is given below. Using the [Date Math Syntax](https://newsapi.aylien.com/docs/working-with-dates), you can easily set your query to return information from any time period, from the current point in time to when the News API started collecting stories. The returned information can be rounded to a time also specified by you, for example by setting the results into hourly, daily, or weekly data points. 
    # @param [Hash] opts the optional parameters
    # @option opts [Array<Integer>] :id This parameter is used for finding stories by story id. 
    # @option opts [Array<Integer>] :id2 This parameter is used for excluding stories by story id. 
    # @option opts [String] :title This parameter is used for finding stories whose title contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :body This parameter is used for finding stories whose body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :text This parameter is used for finding stories whose title or body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_title This parameter is used for finding stories whose translation title contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_body This parameter is used for finding stories whose translation body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [String] :translations_en_text This parameter is used for finding stories whose translation title or body contains a specific keyword. It supports [boolean operators](https://newsapi.aylien.com/docs/boolean-operators). 
    # @option opts [Array<String>] :language This parameter is used for finding stories whose language is the specified value. It supports [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes. 
    # @option opts [Array<String>] :language2 This parameter is used for excluding stories whose language is the specified value. It supports [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language codes. 
    # @option opts [String] :categories_taxonomy This parameter is used for defining the type of the taxonomy for the rest of the categories queries. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Boolean] :categories_confident This parameter is used for finding stories whose categories are confident. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_id This parameter is used for finding stories by categories id. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_id2 This parameter is used for excluding stories by categories id. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_label This parameter is used for finding stories by categories label. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :categories_label2 This parameter is used for excluding stories by categories label. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<Integer>] :categories_level This parameter is used for finding stories by categories level. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<Integer>] :categories_level2 This parameter is used for excluding stories by categories level. You can read more about working with categories [here](https://newsapi.aylien.com/docs/working-with-categories). 
    # @option opts [Array<String>] :entities_title_text This parameter is used to find stories based on the specified entities &#x60;text&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_text2 This parameter is used to exclude stories based on the specified entities &#x60;text&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_type This parameter is used to find stories based on the specified entities &#x60;type&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_type2 This parameter is used to exclude stories based on the specified entities &#x60;type&#x60; in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_links_dbpedia This parameter is used to find stories based on the specified entities dbpedia URL in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_title_links_dbpedia2 This parameter is used to exclude stories based on the specified entities dbpedia URL in story titles. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_text This parameter is used to find stories based on the specified entities &#x60;text&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_text2 This parameter is used to exclude stories based on the specified entities &#x60;text&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_type This parameter is used to find stories based on the specified entities &#x60;type&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_type2 This parameter is used to exclude stories based on the specified entities &#x60;type&#x60; in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_links_dbpedia This parameter is used to find stories based on the specified entities dbpedia URL in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [Array<String>] :entities_body_links_dbpedia2 This parameter is used to exclude stories based on the specified entities dbpedia URL in the body of stories. You can read more about working with entities [here](https://newsapi.aylien.com/docs/working-with-entities). 
    # @option opts [String] :sentiment_title_polarity This parameter is used for finding stories whose title sentiment is the specified value. 
    # @option opts [String] :sentiment_title_polarity2 This parameter is used for excluding stories whose title sentiment is the specified value. 
    # @option opts [String] :sentiment_body_polarity This parameter is used for finding stories whose body sentiment is the specified value. 
    # @option opts [String] :sentiment_body_polarity2 This parameter is used for excluding stories whose body sentiment is the specified value. 
    # @option opts [Integer] :media_images_count_min This parameter is used for finding stories whose number of images is greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_count_max This parameter is used for finding stories whose number of images is less than or equal to the specified value. 
    # @option opts [Integer] :media_images_width_min This parameter is used for finding stories whose width of images are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_width_max This parameter is used for finding stories whose width of images are less than or equal to the specified value. 
    # @option opts [Integer] :media_images_height_min This parameter is used for finding stories whose height of images are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_height_max This parameter is used for finding stories whose height of images are less than or equal to the specified value. 
    # @option opts [Integer] :media_images_content_length_min This parameter is used for finding stories whose images content length are greater than or equal to the specified value. 
    # @option opts [Integer] :media_images_content_length_max This parameter is used for finding stories whose images content length are less than or equal to the specified value. 
    # @option opts [Array<String>] :media_images_format This parameter is used for finding stories whose images format are the specified value. 
    # @option opts [Array<String>] :media_images_format2 This parameter is used for excluding stories whose images format are the specified value. 
    # @option opts [Integer] :media_videos_count_min This parameter is used for finding stories whose number of videos is greater than or equal to the specified value. 
    # @option opts [Integer] :media_videos_count_max This parameter is used for finding stories whose number of videos is less than or equal to the specified value. 
    # @option opts [Array<Integer>] :author_id This parameter is used for finding stories whose author id is the specified value. 
    # @option opts [Array<Integer>] :author_id2 This parameter is used for excluding stories whose author id is the specified value. 
    # @option opts [String] :author_name This parameter is used for finding stories whose author full name contains the specified value. 
    # @option opts [String] :author_name2 This parameter is used for excluding stories whose author full name contains the specified value. 
    # @option opts [Array<Integer>] :source_id This parameter is used for finding stories whose source id is the specified value. 
    # @option opts [Array<Integer>] :source_id2 This parameter is used for excluding stories whose source id is the specified value. 
    # @option opts [Array<String>] :source_name This parameter is used for finding stories whose source name contains the specified value. 
    # @option opts [Array<String>] :source_name2 This parameter is used for excluding stories whose source name contains the specified value. 
    # @option opts [Array<String>] :source_domain This parameter is used for finding stories whose source domain is the specified value. 
    # @option opts [Array<String>] :source_domain2 This parameter is used for excluding stories whose source domain is the specified value. 
    # @option opts [Array<String>] :source_locations_country This parameter is used for finding stories whose source country is the specified value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_country2 This parameter is used for excluding stories whose source country is the specified value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_state This parameter is used for finding stories whose source state/province is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_state2 This parameter is used for excluding stories whose source state/province is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_city This parameter is used for finding stories whose source city is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_locations_city2 This parameter is used for excluding stories whose source city is the specified value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_country This parameter is used for finding stories whose source scopes is the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_country2 This parameter is used for excluding stories whose source scopes is the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_state This parameter is used for finding stories whose source scopes is the specified state/province value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_state2 This parameter is used for excluding stories whose source scopes is the specified state/province value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_city This parameter is used for finding stories whose source scopes is the specified city value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_city2 This parameter is used for excluding stories whose source scopes is the specified city value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_level This parameter is used for finding stories whose source scopes is the specified level value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Array<String>] :source_scopes_level2 This parameter is used for excluding stories whose source scopes is the specified level value. [Here](https://newsapi.aylien.com/docs/working-with-locations) you can find more information about how [to work with locations](https://newsapi.aylien.com/docs/working-with-locations). 
    # @option opts [Integer] :source_links_in_count_min This parameter is used for finding stories from sources whose Links in count is greater than or equal to the specified value. You can read more about working with Links in count [here](https://newsapi.aylien.com/docs/working-with-links-in-count). 
    # @option opts [Integer] :source_links_in_count_max This parameter is used for finding stories from sources whose Links in count is less than or equal to the specified value. You can read more about working with Links in count [here](https://newsapi.aylien.com/docs/working-with-links-in-count). 
    # @option opts [Integer] :source_rankings_alexa_rank_min This parameter is used for finding stories from sources whose Alexa rank is greater than or equal to the specified value. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Integer] :source_rankings_alexa_rank_max This parameter is used for finding stories from sources whose Alexa rank is less than or equal to the specified value. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Array<String>] :source_rankings_alexa_country This parameter is used for finding stories from sources whose Alexa rank is in the specified country value. It supports [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes. You can read more about working with Alexa ranks [here](https://newsapi.aylien.com/docs/working-with-alexa-ranks). 
    # @option opts [Integer] :social_shares_count_facebook_min This parameter is used for finding stories whose Facebook social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_facebook_max This parameter is used for finding stories whose Facebook social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_google_plus_min This parameter is used for finding stories whose Google+ social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_google_plus_max This parameter is used for finding stories whose Google+ social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_linkedin_min This parameter is used for finding stories whose LinkedIn social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_linkedin_max This parameter is used for finding stories whose LinkedIn social shares count is less than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_reddit_min This parameter is used for finding stories whose Reddit social shares count is greater than or equal to the specified value. 
    # @option opts [Integer] :social_shares_count_reddit_max This parameter is used for finding stories whose Reddit social shares count is less than or equal to the specified value. 
    # @option opts [Array<String>] :clusters This parameter is used for finding stories with belonging to one of clusters in a specific set of clusters You can read more about working with clustering [here](https://newsapi.aylien.com/docs/working-with-clustering). 
    # @option opts [String] :published_at_start This parameter is used for finding stories whose published at time is less than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :published_at_end This parameter is used for finding stories whose published at time is greater than the specified value. [Here](https://newsapi.aylien.com/docs/working-with-dates) you can find more information about how [to work with dates](https://newsapi.aylien.com/docs/working-with-dates). 
    # @option opts [String] :period The size of each date range is expressed as an interval to be added to the lower bound. It supports Date Math Syntax. Valid options are &#x60;+&#x60; following an integer number greater than 0 and one of the Date Math keywords. e.g. &#x60;+1DAY&#x60;, &#x60;+2MINUTES&#x60; and &#x60;+1MONTH&#x60;. Here are [Supported keywords](https://newsapi.aylien.com/docs/working-with-dates#date-math). 
    # @return [Array<(TimeSeriesList, Integer, Hash)>] TimeSeriesList data, response status code and response headers
    def list_time_series_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TimeSeriesApi.list_time_series ...'
      end
      allowable_values = ["en", "de", "fr", "it", "es", "pt"]
      if @api_client.config.client_side_validation && opts[:'language'] && !opts[:'language'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"language\", must include one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "it", "es", "pt"]
      if @api_client.config.client_side_validation && opts[:'language2'] && !opts[:'language2'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"language2\", must include one of #{allowable_values}"
      end
      allowable_values = ["iab-qag", "iptc-subjectcode"]
      if @api_client.config.client_side_validation && opts[:'categories_taxonomy'] && !allowable_values.include?(opts[:'categories_taxonomy'])
        fail ArgumentError, "invalid value for \"categories_taxonomy\", must be one of #{allowable_values}"
      end
      allowable_values = ["positive", "neutral", "negative"]
      if @api_client.config.client_side_validation && opts[:'sentiment_title_polarity'] && !allowable_values.include?(opts[:'sentiment_title_polarity'])
        fail ArgumentError, "invalid value for \"sentiment_title_polarity\", must be one of #{allowable_values}"
      end
      allowable_values = ["positive", "neutral", "negative"]
      if @api_client.config.client_side_validation && opts[:'sentiment_title_polarity2'] && !allowable_values.include?(opts[:'sentiment_title_polarity2'])
        fail ArgumentError, "invalid value for \"sentiment_title_polarity2\", must be one of #{allowable_values}"
      end
      allowable_values = ["positive", "neutral", "negative"]
      if @api_client.config.client_side_validation && opts[:'sentiment_body_polarity'] && !allowable_values.include?(opts[:'sentiment_body_polarity'])
        fail ArgumentError, "invalid value for \"sentiment_body_polarity\", must be one of #{allowable_values}"
      end
      allowable_values = ["positive", "neutral", "negative"]
      if @api_client.config.client_side_validation && opts[:'sentiment_body_polarity2'] && !allowable_values.include?(opts[:'sentiment_body_polarity2'])
        fail ArgumentError, "invalid value for \"sentiment_body_polarity2\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'media_images_count_min'].nil? && opts[:'media_images_count_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_count_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_count_max'].nil? && opts[:'media_images_count_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_count_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_width_min'].nil? && opts[:'media_images_width_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_width_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_width_max'].nil? && opts[:'media_images_width_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_width_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_height_min'].nil? && opts[:'media_images_height_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_height_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_height_max'].nil? && opts[:'media_images_height_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_height_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_content_length_min'].nil? && opts[:'media_images_content_length_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_content_length_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_images_content_length_max'].nil? && opts[:'media_images_content_length_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_images_content_length_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      allowable_values = ["BMP", "GIF", "JPEG", "PNG", "TIFF", "PSD", "ICO", "CUR", "WEBP", "SVG"]
      if @api_client.config.client_side_validation && opts[:'media_images_format'] && !opts[:'media_images_format'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"media_images_format\", must include one of #{allowable_values}"
      end
      allowable_values = ["BMP", "GIF", "JPEG", "PNG", "TIFF", "PSD", "ICO", "CUR", "WEBP", "SVG"]
      if @api_client.config.client_side_validation && opts[:'media_images_format2'] && !opts[:'media_images_format2'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"media_images_format2\", must include one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'media_videos_count_min'].nil? && opts[:'media_videos_count_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_videos_count_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'media_videos_count_max'].nil? && opts[:'media_videos_count_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"media_videos_count_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      allowable_values = ["international", "national", "local"]
      if @api_client.config.client_side_validation && opts[:'source_scopes_level'] && !opts[:'source_scopes_level'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"source_scopes_level\", must include one of #{allowable_values}"
      end
      allowable_values = ["international", "national", "local"]
      if @api_client.config.client_side_validation && opts[:'source_scopes_level2'] && !opts[:'source_scopes_level2'].all? { |item| allowable_values.include?(item) }
        fail ArgumentError, "invalid value for \"source_scopes_level2\", must include one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'source_links_in_count_min'].nil? && opts[:'source_links_in_count_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"source_links_in_count_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'source_links_in_count_max'].nil? && opts[:'source_links_in_count_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"source_links_in_count_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'source_rankings_alexa_rank_min'].nil? && opts[:'source_rankings_alexa_rank_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"source_rankings_alexa_rank_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'source_rankings_alexa_rank_max'].nil? && opts[:'source_rankings_alexa_rank_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"source_rankings_alexa_rank_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_facebook_min'].nil? && opts[:'social_shares_count_facebook_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_facebook_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_facebook_max'].nil? && opts[:'social_shares_count_facebook_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_facebook_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_google_plus_min'].nil? && opts[:'social_shares_count_google_plus_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_google_plus_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_google_plus_max'].nil? && opts[:'social_shares_count_google_plus_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_google_plus_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_linkedin_min'].nil? && opts[:'social_shares_count_linkedin_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_linkedin_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_linkedin_max'].nil? && opts[:'social_shares_count_linkedin_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_linkedin_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_reddit_min'].nil? && opts[:'social_shares_count_reddit_min'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_reddit_min"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'social_shares_count_reddit_max'].nil? && opts[:'social_shares_count_reddit_max'] <= 0
        fail ArgumentError, 'invalid value for "opts[:"social_shares_count_reddit_max"]" when calling TimeSeriesApi.list_time_series, must be greater than 0.'
      end

      # resource path
      local_var_path = '/time_series'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'id[]'] = @api_client.build_collection_param(opts[:'id'], :multi) if !opts[:'id'].nil?
      query_params[:'!id[]'] = @api_client.build_collection_param(opts[:'id2'], :multi) if !opts[:'id2'].nil?
      query_params[:'title'] = opts[:'title'] if !opts[:'title'].nil?
      query_params[:'body'] = opts[:'body'] if !opts[:'body'].nil?
      query_params[:'text'] = opts[:'text'] if !opts[:'text'].nil?
      query_params[:'translations.en.title'] = opts[:'translations_en_title'] if !opts[:'translations_en_title'].nil?
      query_params[:'translations.en.body'] = opts[:'translations_en_body'] if !opts[:'translations_en_body'].nil?
      query_params[:'translations.en.text'] = opts[:'translations_en_text'] if !opts[:'translations_en_text'].nil?
      query_params[:'language[]'] = @api_client.build_collection_param(opts[:'language'], :multi) if !opts[:'language'].nil?
      query_params[:'!language[]'] = @api_client.build_collection_param(opts[:'language2'], :multi) if !opts[:'language2'].nil?
      query_params[:'categories.taxonomy'] = opts[:'categories_taxonomy'] if !opts[:'categories_taxonomy'].nil?
      query_params[:'categories.confident'] = opts[:'categories_confident'] if !opts[:'categories_confident'].nil?
      query_params[:'categories.id[]'] = @api_client.build_collection_param(opts[:'categories_id'], :multi) if !opts[:'categories_id'].nil?
      query_params[:'!categories.id[]'] = @api_client.build_collection_param(opts[:'categories_id2'], :multi) if !opts[:'categories_id2'].nil?
      query_params[:'categories.label[]'] = @api_client.build_collection_param(opts[:'categories_label'], :multi) if !opts[:'categories_label'].nil?
      query_params[:'!categories.label[]'] = @api_client.build_collection_param(opts[:'categories_label2'], :multi) if !opts[:'categories_label2'].nil?
      query_params[:'categories.level[]'] = @api_client.build_collection_param(opts[:'categories_level'], :multi) if !opts[:'categories_level'].nil?
      query_params[:'!categories.level[]'] = @api_client.build_collection_param(opts[:'categories_level2'], :multi) if !opts[:'categories_level2'].nil?
      query_params[:'entities.title.text[]'] = @api_client.build_collection_param(opts[:'entities_title_text'], :multi) if !opts[:'entities_title_text'].nil?
      query_params[:'!entities.title.text[]'] = @api_client.build_collection_param(opts[:'entities_title_text2'], :multi) if !opts[:'entities_title_text2'].nil?
      query_params[:'entities.title.type[]'] = @api_client.build_collection_param(opts[:'entities_title_type'], :multi) if !opts[:'entities_title_type'].nil?
      query_params[:'!entities.title.type[]'] = @api_client.build_collection_param(opts[:'entities_title_type2'], :multi) if !opts[:'entities_title_type2'].nil?
      query_params[:'entities.title.links.dbpedia[]'] = @api_client.build_collection_param(opts[:'entities_title_links_dbpedia'], :multi) if !opts[:'entities_title_links_dbpedia'].nil?
      query_params[:'!entities.title.links.dbpedia[]'] = @api_client.build_collection_param(opts[:'entities_title_links_dbpedia2'], :multi) if !opts[:'entities_title_links_dbpedia2'].nil?
      query_params[:'entities.body.text[]'] = @api_client.build_collection_param(opts[:'entities_body_text'], :multi) if !opts[:'entities_body_text'].nil?
      query_params[:'!entities.body.text[]'] = @api_client.build_collection_param(opts[:'entities_body_text2'], :multi) if !opts[:'entities_body_text2'].nil?
      query_params[:'entities.body.type[]'] = @api_client.build_collection_param(opts[:'entities_body_type'], :multi) if !opts[:'entities_body_type'].nil?
      query_params[:'!entities.body.type[]'] = @api_client.build_collection_param(opts[:'entities_body_type2'], :multi) if !opts[:'entities_body_type2'].nil?
      query_params[:'entities.body.links.dbpedia[]'] = @api_client.build_collection_param(opts[:'entities_body_links_dbpedia'], :multi) if !opts[:'entities_body_links_dbpedia'].nil?
      query_params[:'!entities.body.links.dbpedia[]'] = @api_client.build_collection_param(opts[:'entities_body_links_dbpedia2'], :multi) if !opts[:'entities_body_links_dbpedia2'].nil?
      query_params[:'sentiment.title.polarity'] = opts[:'sentiment_title_polarity'] if !opts[:'sentiment_title_polarity'].nil?
      query_params[:'!sentiment.title.polarity'] = opts[:'sentiment_title_polarity2'] if !opts[:'sentiment_title_polarity2'].nil?
      query_params[:'sentiment.body.polarity'] = opts[:'sentiment_body_polarity'] if !opts[:'sentiment_body_polarity'].nil?
      query_params[:'!sentiment.body.polarity'] = opts[:'sentiment_body_polarity2'] if !opts[:'sentiment_body_polarity2'].nil?
      query_params[:'media.images.count.min'] = opts[:'media_images_count_min'] if !opts[:'media_images_count_min'].nil?
      query_params[:'media.images.count.max'] = opts[:'media_images_count_max'] if !opts[:'media_images_count_max'].nil?
      query_params[:'media.images.width.min'] = opts[:'media_images_width_min'] if !opts[:'media_images_width_min'].nil?
      query_params[:'media.images.width.max'] = opts[:'media_images_width_max'] if !opts[:'media_images_width_max'].nil?
      query_params[:'media.images.height.min'] = opts[:'media_images_height_min'] if !opts[:'media_images_height_min'].nil?
      query_params[:'media.images.height.max'] = opts[:'media_images_height_max'] if !opts[:'media_images_height_max'].nil?
      query_params[:'media.images.content_length.min'] = opts[:'media_images_content_length_min'] if !opts[:'media_images_content_length_min'].nil?
      query_params[:'media.images.content_length.max'] = opts[:'media_images_content_length_max'] if !opts[:'media_images_content_length_max'].nil?
      query_params[:'media.images.format[]'] = @api_client.build_collection_param(opts[:'media_images_format'], :multi) if !opts[:'media_images_format'].nil?
      query_params[:'!media.images.format[]'] = @api_client.build_collection_param(opts[:'media_images_format2'], :multi) if !opts[:'media_images_format2'].nil?
      query_params[:'media.videos.count.min'] = opts[:'media_videos_count_min'] if !opts[:'media_videos_count_min'].nil?
      query_params[:'media.videos.count.max'] = opts[:'media_videos_count_max'] if !opts[:'media_videos_count_max'].nil?
      query_params[:'author.id[]'] = @api_client.build_collection_param(opts[:'author_id'], :multi) if !opts[:'author_id'].nil?
      query_params[:'!author.id[]'] = @api_client.build_collection_param(opts[:'author_id2'], :multi) if !opts[:'author_id2'].nil?
      query_params[:'author.name'] = opts[:'author_name'] if !opts[:'author_name'].nil?
      query_params[:'!author.name'] = opts[:'author_name2'] if !opts[:'author_name2'].nil?
      query_params[:'source.id[]'] = @api_client.build_collection_param(opts[:'source_id'], :multi) if !opts[:'source_id'].nil?
      query_params[:'!source.id[]'] = @api_client.build_collection_param(opts[:'source_id2'], :multi) if !opts[:'source_id2'].nil?
      query_params[:'source.name[]'] = @api_client.build_collection_param(opts[:'source_name'], :multi) if !opts[:'source_name'].nil?
      query_params[:'!source.name[]'] = @api_client.build_collection_param(opts[:'source_name2'], :multi) if !opts[:'source_name2'].nil?
      query_params[:'source.domain[]'] = @api_client.build_collection_param(opts[:'source_domain'], :multi) if !opts[:'source_domain'].nil?
      query_params[:'!source.domain[]'] = @api_client.build_collection_param(opts[:'source_domain2'], :multi) if !opts[:'source_domain2'].nil?
      query_params[:'source.locations.country[]'] = @api_client.build_collection_param(opts[:'source_locations_country'], :multi) if !opts[:'source_locations_country'].nil?
      query_params[:'!source.locations.country[]'] = @api_client.build_collection_param(opts[:'source_locations_country2'], :multi) if !opts[:'source_locations_country2'].nil?
      query_params[:'source.locations.state[]'] = @api_client.build_collection_param(opts[:'source_locations_state'], :multi) if !opts[:'source_locations_state'].nil?
      query_params[:'!source.locations.state[]'] = @api_client.build_collection_param(opts[:'source_locations_state2'], :multi) if !opts[:'source_locations_state2'].nil?
      query_params[:'source.locations.city[]'] = @api_client.build_collection_param(opts[:'source_locations_city'], :multi) if !opts[:'source_locations_city'].nil?
      query_params[:'!source.locations.city[]'] = @api_client.build_collection_param(opts[:'source_locations_city2'], :multi) if !opts[:'source_locations_city2'].nil?
      query_params[:'source.scopes.country[]'] = @api_client.build_collection_param(opts[:'source_scopes_country'], :multi) if !opts[:'source_scopes_country'].nil?
      query_params[:'!source.scopes.country[]'] = @api_client.build_collection_param(opts[:'source_scopes_country2'], :multi) if !opts[:'source_scopes_country2'].nil?
      query_params[:'source.scopes.state[]'] = @api_client.build_collection_param(opts[:'source_scopes_state'], :multi) if !opts[:'source_scopes_state'].nil?
      query_params[:'!source.scopes.state[]'] = @api_client.build_collection_param(opts[:'source_scopes_state2'], :multi) if !opts[:'source_scopes_state2'].nil?
      query_params[:'source.scopes.city[]'] = @api_client.build_collection_param(opts[:'source_scopes_city'], :multi) if !opts[:'source_scopes_city'].nil?
      query_params[:'!source.scopes.city[]'] = @api_client.build_collection_param(opts[:'source_scopes_city2'], :multi) if !opts[:'source_scopes_city2'].nil?
      query_params[:'source.scopes.level[]'] = @api_client.build_collection_param(opts[:'source_scopes_level'], :multi) if !opts[:'source_scopes_level'].nil?
      query_params[:'!source.scopes.level[]'] = @api_client.build_collection_param(opts[:'source_scopes_level2'], :multi) if !opts[:'source_scopes_level2'].nil?
      query_params[:'source.links_in_count.min'] = opts[:'source_links_in_count_min'] if !opts[:'source_links_in_count_min'].nil?
      query_params[:'source.links_in_count.max'] = opts[:'source_links_in_count_max'] if !opts[:'source_links_in_count_max'].nil?
      query_params[:'source.rankings.alexa.rank.min'] = opts[:'source_rankings_alexa_rank_min'] if !opts[:'source_rankings_alexa_rank_min'].nil?
      query_params[:'source.rankings.alexa.rank.max'] = opts[:'source_rankings_alexa_rank_max'] if !opts[:'source_rankings_alexa_rank_max'].nil?
      query_params[:'source.rankings.alexa.country[]'] = @api_client.build_collection_param(opts[:'source_rankings_alexa_country'], :multi) if !opts[:'source_rankings_alexa_country'].nil?
      query_params[:'social_shares_count.facebook.min'] = opts[:'social_shares_count_facebook_min'] if !opts[:'social_shares_count_facebook_min'].nil?
      query_params[:'social_shares_count.facebook.max'] = opts[:'social_shares_count_facebook_max'] if !opts[:'social_shares_count_facebook_max'].nil?
      query_params[:'social_shares_count.google_plus.min'] = opts[:'social_shares_count_google_plus_min'] if !opts[:'social_shares_count_google_plus_min'].nil?
      query_params[:'social_shares_count.google_plus.max'] = opts[:'social_shares_count_google_plus_max'] if !opts[:'social_shares_count_google_plus_max'].nil?
      query_params[:'social_shares_count.linkedin.min'] = opts[:'social_shares_count_linkedin_min'] if !opts[:'social_shares_count_linkedin_min'].nil?
      query_params[:'social_shares_count.linkedin.max'] = opts[:'social_shares_count_linkedin_max'] if !opts[:'social_shares_count_linkedin_max'].nil?
      query_params[:'social_shares_count.reddit.min'] = opts[:'social_shares_count_reddit_min'] if !opts[:'social_shares_count_reddit_min'].nil?
      query_params[:'social_shares_count.reddit.max'] = opts[:'social_shares_count_reddit_max'] if !opts[:'social_shares_count_reddit_max'].nil?
      query_params[:'clusters[]'] = @api_client.build_collection_param(opts[:'clusters'], :multi) if !opts[:'clusters'].nil?
      query_params[:'published_at.start'] = opts[:'published_at_start'] if !opts[:'published_at_start'].nil?
      query_params[:'published_at.end'] = opts[:'published_at_end'] if !opts[:'published_at_end'].nil?
      query_params[:'period'] = opts[:'period'] if !opts[:'period'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'text/xml'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'TimeSeriesList' 

      # auth_names
      auth_names = opts[:auth_names] || ['app_id', 'app_key']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TimeSeriesApi#list_time_series\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
